input {
  beats {
    port => 5044
  }
  http {
    port => 8080
    codec => json
  }
}

filter {
  if [alert_type] {
    mutate {
      add_field => { "[@metadata][index]" => "ids-alerts" }
    }
  } else {
    mutate {
      add_field => { "[@metadata][index]" => "ids-traffic" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "%{[@metadata][index]}-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}